'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { BookOpen, Brain, Zap, Target, ArrowRight, Github, Star } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { ResearchForm } from '@/components/research-form'
import { Header } from '@/components/header'
import { useAuth } from '@/lib/hooks/use-auth'
import { useRouter } from 'next/navigation'
import Link from 'next/link'

// Force dynamic rendering
export const dynamic = 'force-dynamic'

export default function HomePage() {
  const [showResearchForm, setShowResearchForm] = useState(false)
  const { isAuthenticated } = useAuth()
  const router = useRouter()

  const handleStartResearch = () => {
    if (isAuthenticated) {
      router.push('/dashboard')
    } else {
      setShowResearchForm(true)
    }
  }

  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Research',
      description: 'Advanced AI agents conduct comprehensive research using multiple sources and intelligent analysis.'
    },
    {
      icon: Zap,
      title: 'Lightning Fast',
      description: 'Generate complete research papers in minutes, not weeks. Automated outline generation and content creation.'
    },
    {
      icon: Target,
      title: 'Precision & Quality',
      description: 'Smart fact-checking, citation management, and quality scoring ensure academic standards.'
    },
    {
      icon: BookOpen,
      title: 'Multiple Formats',
      description: 'Export to PDF, DOCX, Markdown, and LaTeX. Support for various citation styles (APA, MLA, Chicago).'
    }
  ]

  return (
    <div className="min-h-screen">
      <Header />
      
      {/* Hero Section */}
      <section className="relative py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold text-gray-900 dark:text-white mb-6">
                Research Papers
                <span className="block text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">
                  Generated by AI
                </span>
              </h1>
              
              <p className="text-xl md:text-2xl text-gray-600 dark:text-gray-300 mb-8 max-w-3xl mx-auto">
                Drop in your research topic and watch our AI agents create comprehensive, 
                well-researched papers with proper citations and formatting.
              </p>

              <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-12">
                <Button 
                  size="lg" 
                  className="text-lg px-8 py-6 animate-pulse-glow"
                  onClick={() => setShowResearchForm(true)}
                >
                  Start Research <ArrowRight className="ml-2 h-5 w-5" />
                </Button>
                
                <Button variant="outline" size="lg" className="text-lg px-8 py-6" asChild>
                  <Link href="https://github.com/your-repo/research-agent" target="_blank">
                    <Github className="mr-2 h-5 w-5" />
                    View on GitHub
                  </Link>
                </Button>
              </div>

              <div className="flex items-center justify-center gap-6 text-sm text-gray-500 dark:text-gray-400">
                <div className="flex items-center gap-1">
                  <Star className="h-4 w-4 text-yellow-500" />
                  <span>1.2k stars</span>
                </div>
                <div>•</div>
                <div>Open Source</div>
                <div>•</div>
                <div>Free to Use</div>
              </div>
            </motion.div>
          </div>
        </div>

        {/* Floating Elements */}
        <div className="absolute top-20 left-10 w-20 h-20 bg-blue-200 dark:bg-blue-800 rounded-full opacity-20 animate-float"></div>
        <div className="absolute top-40 right-20 w-16 h-16 bg-purple-200 dark:bg-purple-800 rounded-full opacity-20 animate-float" style={{ animationDelay: '2s' }}></div>
        <div className="absolute bottom-20 left-20 w-12 h-12 bg-indigo-200 dark:bg-indigo-800 rounded-full opacity-20 animate-float" style={{ animationDelay: '4s' }}></div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
              Powerful AI Research Assistant
            </h2>
            <p className="text-xl text-gray-600 dark:text-gray-300 max-w-2xl mx-auto">
              Experience the future of academic research with our advanced AI agent system
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.1 * index }}
              >
                <Card className="h-full glass-effect hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1">
                  <CardHeader>
                    <feature.icon className="h-10 w-10 text-blue-600 dark:text-blue-400 mb-4" />
                    <CardTitle className="text-xl">{feature.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <CardDescription className="text-base">
                      {feature.description}
                    </CardDescription>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-white/50 dark:bg-slate-900/50">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
              How It Works
            </h2>
            <p className="text-xl text-gray-600 dark:text-gray-300">
              Three simple steps to generate your research paper
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-12">
            {[
              {
                step: '01',
                title: 'Input Your Topic',
                description: 'Simply enter your research topic and specify your preferences for style, length, and citation format.'
              },
              {
                step: '02',
                title: 'AI Agents Work',
                description: 'Our specialized agents search the web, analyze content, and create a comprehensive outline with sources.'
              },
              {
                step: '03',
                title: 'Download Your Paper',
                description: 'Receive a fully formatted research paper with proper citations, ready for submission or publication.'
              }
            ].map((step, index) => (
              <motion.div
                key={step.step}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.6, delay: 0.2 * index }}
                className="text-center"
              >
                <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-r from-blue-600 to-purple-600 text-white text-2xl font-bold mb-6">
                  {step.step}
                </div>
                <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
                  {step.title}
                </h3>
                <p className="text-gray-600 dark:text-gray-300 text-lg">
                  {step.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-4xl font-bold text-gray-900 dark:text-white mb-6">
              Ready to Transform Your Research?
            </h2>
            <p className="text-xl text-gray-600 dark:text-gray-300 mb-8">
              Join thousands of researchers, students, and professionals who use our AI-powered platform
            </p>
            <Button 
              size="lg" 
              className="text-lg px-12 py-6 animate-pulse-glow"
              onClick={handleStartResearch}
            >
              {isAuthenticated ? 'Go to Dashboard' : 'Generate Your First Paper'} <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </motion.div>
        </div>
      </section>

      {/* Research Form Modal - Only show if not authenticated */}
      {showResearchForm && !isAuthenticated && (
        <ResearchForm onClose={() => setShowResearchForm(false)} />
      )}
    </div>
  )
}
